alter table SEC_USER change column GROUP_NAMES GROUP_NAMES__U79754 varchar(255)^
alter table SEC_USER change column PASSWORD_ENCRYPTION PASSWORD_ENCRYPTION__U71339 varchar(50)^
alter table SEC_USER change column SYS_TENANT_ID_NN SYS_TENANT_ID_NN__U91548 varchar(255)^
alter table SEC_USER change column SYS_TENANT_ID SYS_TENANT_ID__U82665 varchar(255)^
alter table SEC_USER change column PASSWORD_ENCRYPTION PASSWORD_ENCRYPTION__U21081 varchar(50)^
alter table SEC_USER change column PASSWORD_ENCRYPTION PASSWORD_ENCRYPTION__U42482 varchar(50)^
alter table SEC_USER change column GROUP_NAMES GROUP_NAMES__U60649 varchar(255)^
alter table SEC_USER change column PASSWORD_ENCRYPTION PASSWORD_ENCRYPTION__U70820 varchar(50)^
alter table SEC_USER change column SYS_TENANT_ID_NN SYS_TENANT_ID_NN__U43904 varchar(255)^
alter table SEC_USER change column SYS_TENANT_ID SYS_TENANT_ID__U40892 varchar(255)^
alter table SEC_USER change column PASSWORD_ENCRYPTION PASSWORD_ENCRYPTION__U64716 varchar(50)^
alter table SEC_USER change column SYS_TENANT_ID_NN SYS_TENANT_ID_NN__U39712 varchar(255)^
